name: 'Sign by issue action'
description: 'Github action for signing by creating issues'
inputs:
  github-token:
    description: 'A GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'trending-up'
  color: 'purple'
